server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: test
    password: test
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: false

# Log
logging:
  level:
    com.today25.userservice: DEBUG # log4j 로그 개발서버는: debug, 운영은: info
    org.springframework: error
    org.hibernate.SQL: debug
    org.apache.coyote.http11: debug # HTTP PRINT

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

greeting:
  message: Welcome to the User Service

# actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans

# JWT -> config-server
#token:
#  expiration_time: 86400000
#  secret: 611c94a633cadd552aa47e164541c3c47f419ff5250783bea2b435ef0b75f25e895f966c290004bd97249e26089e75e8aff922b412a14059468dc28e97c1219e





